/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CtSlugRouteImport } from './routes/ct.$slug'
import { Route as AppTutorialsRouteImport } from './routes/app.tutorials'
import { Route as AppStoreRouteImport } from './routes/app.store'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSalesRouteImport } from './routes/app.sales'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppReferralRouteImport } from './routes/app.referral'
import { Route as AppReceivablesRouteImport } from './routes/app.receivables'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppExpensesRouteImport } from './routes/app.expenses'
import { Route as AppCrmRouteImport } from './routes/app.crm'
import { Route as AppChannelsRouteImport } from './routes/app.channels'
import { Route as AppCategoriesRouteImport } from './routes/app.categories'
import { Route as AppCatalogRouteImport } from './routes/app.catalog'
import { Route as AppCashflowRouteImport } from './routes/app.cashflow'
import { Route as AppAutomationsRouteImport } from './routes/app.automations'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as ApiWebhookRouteImport } from './routes/api/webhook'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminFinancialRouteImport } from './routes/admin.financial'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'

const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CtSlugRoute = CtSlugRouteImport.update({
  id: '/ct/$slug',
  path: '/ct/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTutorialsRoute = AppTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreRoute = AppStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralRoute = AppReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AppRoute,
} as any)
const AppReceivablesRoute = AppReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsRoute = AppChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppCashflowRoute = AppCashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiWebhookRoute = ApiWebhookRouteImport.update({
  id: '/api/webhook',
  path: '/api/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancialRoute = AdminFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/obrigado': typeof ObrigadoRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/financial': typeof AdminFinancialRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/cashflow': typeof AppCashflowRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/channels': typeof AppChannelsRoute
  '/app/crm': typeof AppCrmRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/products': typeof AppProductsRoute
  '/app/receivables': typeof AppReceivablesRoute
  '/app/referral': typeof AppReferralRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/store': typeof AppStoreRoute
  '/app/tutorials': typeof AppTutorialsRoute
  '/ct/$slug': typeof CtSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/obrigado': typeof ObrigadoRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/financial': typeof AdminFinancialRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/cashflow': typeof AppCashflowRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/channels': typeof AppChannelsRoute
  '/app/crm': typeof AppCrmRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/products': typeof AppProductsRoute
  '/app/receivables': typeof AppReceivablesRoute
  '/app/referral': typeof AppReferralRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/store': typeof AppStoreRoute
  '/app/tutorials': typeof AppTutorialsRoute
  '/ct/$slug': typeof CtSlugRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/obrigado': typeof ObrigadoRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/financial': typeof AdminFinancialRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin_/login': typeof AdminLoginRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/cashflow': typeof AppCashflowRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/channels': typeof AppChannelsRoute
  '/app/crm': typeof AppCrmRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/products': typeof AppProductsRoute
  '/app/receivables': typeof AppReceivablesRoute
  '/app/referral': typeof AppReferralRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/store': typeof AppStoreRoute
  '/app/tutorials': typeof AppTutorialsRoute
  '/ct/$slug': typeof CtSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/obrigado'
    | '/admin/coupons'
    | '/admin/financial'
    | '/admin/partners'
    | '/admin/users'
    | '/admin/login'
    | '/api/webhook'
    | '/app/analytics'
    | '/app/automations'
    | '/app/cashflow'
    | '/app/catalog'
    | '/app/categories'
    | '/app/channels'
    | '/app/crm'
    | '/app/expenses'
    | '/app/payments'
    | '/app/products'
    | '/app/receivables'
    | '/app/referral'
    | '/app/reports'
    | '/app/sales'
    | '/app/settings'
    | '/app/store'
    | '/app/tutorials'
    | '/ct/$slug'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/obrigado'
    | '/admin/coupons'
    | '/admin/financial'
    | '/admin/partners'
    | '/admin/users'
    | '/admin/login'
    | '/api/webhook'
    | '/app/analytics'
    | '/app/automations'
    | '/app/cashflow'
    | '/app/catalog'
    | '/app/categories'
    | '/app/channels'
    | '/app/crm'
    | '/app/expenses'
    | '/app/payments'
    | '/app/products'
    | '/app/receivables'
    | '/app/referral'
    | '/app/reports'
    | '/app/sales'
    | '/app/settings'
    | '/app/store'
    | '/app/tutorials'
    | '/ct/$slug'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/obrigado'
    | '/admin/coupons'
    | '/admin/financial'
    | '/admin/partners'
    | '/admin/users'
    | '/admin_/login'
    | '/api/webhook'
    | '/app/analytics'
    | '/app/automations'
    | '/app/cashflow'
    | '/app/catalog'
    | '/app/categories'
    | '/app/channels'
    | '/app/crm'
    | '/app/expenses'
    | '/app/payments'
    | '/app/products'
    | '/app/receivables'
    | '/app/referral'
    | '/app/reports'
    | '/app/sales'
    | '/app/settings'
    | '/app/store'
    | '/app/tutorials'
    | '/ct/$slug'
    | '/admin/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ObrigadoRoute: typeof ObrigadoRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiWebhookRoute: typeof ApiWebhookRoute
  CtSlugRoute: typeof CtSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ct/$slug': {
      id: '/ct/$slug'
      path: '/ct/$slug'
      fullPath: '/ct/$slug'
      preLoaderRoute: typeof CtSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tutorials': {
      id: '/app/tutorials'
      path: '/tutorials'
      fullPath: '/app/tutorials'
      preLoaderRoute: typeof AppTutorialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/store': {
      id: '/app/store'
      path: '/store'
      fullPath: '/app/store'
      preLoaderRoute: typeof AppStoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales': {
      id: '/app/sales'
      path: '/sales'
      fullPath: '/app/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/referral': {
      id: '/app/referral'
      path: '/referral'
      fullPath: '/app/referral'
      preLoaderRoute: typeof AppReferralRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/receivables': {
      id: '/app/receivables'
      path: '/receivables'
      fullPath: '/app/receivables'
      preLoaderRoute: typeof AppReceivablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/channels': {
      id: '/app/channels'
      path: '/channels'
      fullPath: '/app/channels'
      preLoaderRoute: typeof AppChannelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories': {
      id: '/app/categories'
      path: '/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalog': {
      id: '/app/catalog'
      path: '/catalog'
      fullPath: '/app/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cashflow': {
      id: '/app/cashflow'
      path: '/cashflow'
      fullPath: '/app/cashflow'
      preLoaderRoute: typeof AppCashflowRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/automations': {
      id: '/app/automations'
      path: '/automations'
      fullPath: '/app/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/webhook': {
      id: '/api/webhook'
      path: '/api/webhook'
      fullPath: '/api/webhook'
      preLoaderRoute: typeof ApiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financial': {
      id: '/admin/financial'
      path: '/financial'
      fullPath: '/admin/financial'
      preLoaderRoute: typeof AdminFinancialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminFinancialRoute: typeof AdminFinancialRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCouponsRoute: AdminCouponsRoute,
  AdminFinancialRoute: AdminFinancialRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppCashflowRoute: typeof AppCashflowRoute
  AppCatalogRoute: typeof AppCatalogRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppChannelsRoute: typeof AppChannelsRoute
  AppCrmRoute: typeof AppCrmRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppProductsRoute: typeof AppProductsRoute
  AppReceivablesRoute: typeof AppReceivablesRoute
  AppReferralRoute: typeof AppReferralRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStoreRoute: typeof AppStoreRoute
  AppTutorialsRoute: typeof AppTutorialsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAutomationsRoute: AppAutomationsRoute,
  AppCashflowRoute: AppCashflowRoute,
  AppCatalogRoute: AppCatalogRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppChannelsRoute: AppChannelsRoute,
  AppCrmRoute: AppCrmRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppProductsRoute: AppProductsRoute,
  AppReceivablesRoute: AppReceivablesRoute,
  AppReferralRoute: AppReferralRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStoreRoute: AppStoreRoute,
  AppTutorialsRoute: AppTutorialsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ObrigadoRoute: ObrigadoRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiWebhookRoute: ApiWebhookRoute,
  CtSlugRoute: CtSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
